Sitecore81Sample/Controllers/NavigationController.cs
using Glass.Mapper.Sc.Web.Mvc;
using Sitecore.Data.Items;
using Sitecore81.Core.Glass;
using Sitecore81Sample.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Sitecore81Sample.Controllers
{
    public class NavigationController : GlassController
    {
        public ActionResult MainNavigation()
        {
            var items = Sitecore.Context.Database.GetItem(Sitecore.Context.Site.StartPath).Children
                .Select(c => SitecoreContext.Cast<IBasePage>(c))
                .Where(c => c.Active && c.Display_In_Menu);

            return PartialView(items);
        }

        public ActionResult FooterNavigation()
        {
            Item item = Sitecore.Context.Database.GetItem(Sitecore.Context.Site.RootPath)?.Children
                .FirstOrDefault(c => c.TemplateID == ISiteDataFolderConstants.TemplateId)?.Children
                .FirstOrDefault(c => c.TemplateID == ISettingsFolderConstants.TemplateId)?.Children
                .FirstOrDefault(c => c.TemplateID == IFooterSettingsConstants.TemplateId);
            FooterSettingsVM vm = new FooterSettingsVM(SitecoreContext.Cast<IFooterSettings>(item));

            return PartialView(vm);
        }
    }
}

Sitecore81Sample/Views/Shared/ExperienceExplorerView.cshtml
@using Sitecore.ExperienceExplorer.Business.Constants;
@using Sitecore.ExperienceExplorer.Business.Helpers;
@using Sitecore.ExperienceExplorer.Business.Managers;
@using Sitecore.Publishing;
@using Sitecore.Web;

@{
    // TODO Figure out how to keep logged in state properly after Page Editor usage
    if (!Sitecore.Context.IsLoggedIn)
    {
        PreviewManager.RestoreUser();
    }

    // Toggle OFF
    var queryString = WebUtil.GetQueryString(SettingsHelper.AddOnQueryStringKey);
    var disabledFromQuery = queryString == "0";
    if (disabledFromQuery || PageModeHelper.IsEditMode || PageModeHelper.IsPreviewMode || PageModeHelper.IsDebugMode)
    {
        ModuleManager.Disable();
        return;
    }

    // Toggle ON
    var enabledFromQuery = queryString == "1";
    if (enabledFromQuery)
    {
        ModuleManager.Enable();
    }



    var isExpViewEnabled = ModuleManager.IsExpViewModeActive;

    if (Sitecore.Context.IsLoggedIn && isExpViewEnabled && PageModeHelper.HasPermission && !PageModeHelper.IsInternalRequest)
    { 
    <link rel="stylesheet" type="text/css" href="/sitecore modules/Web/ExperienceExplorer/Assets/css/experience-explorer.css" />

    <div class="experience-explorer">
      <div class="panel editor">
        <span id="pageEditorHeader"></span>
        <button type="button" class="page-editor-button" onclick="javascript:window.top.location.href='/?sc_mode=edit';">Experience Editor</button>
        <a class="trigger" href="#"></a>
        <iframe scrolling="no" src="@Html.Raw(Paths.Module.Controls.RelativePath)ExpEditor.aspx?@Html.Raw(SettingsHelper.AddOnQueryStringKey)=1&@Html.Raw(SettingsHelper.ContextItemIdQueryStringKey)=@Html.Raw(Sitecore.Context.Item.ID.ToString())&@Html.Raw(SettingsHelper.ContextDeviceIdQueryStringKey)=@Html.Raw(Sitecore.Context.Device.ID.ToString())&@Html.Raw(SettingsHelper.CurrentWebsiteStringKey)=@Html.Raw(Sitecore.Context.Site.Name)&sc_preventProfilesScoring=1&sc_lang=@Html.Raw(Sitecore.ExperienceExplorer.Web.Controls.ExpExplorerExtender.LanguageName)" id="IframeExperienceExplorerEditor" class="ee-iframe"></iframe>
      </div>
        <div class="panel viewer">
            <a class="trigger" href="#"></a>
            <iframe scrolling="no" src="@Html.Raw(Paths.Module.Controls.RelativePath)ExpViewer.aspx?@Html.Raw(SettingsHelper.AddOnQueryStringKey)=1&@Html.Raw(SettingsHelper.ContextItemIdQueryStringKey)=@Html.Raw(Sitecore.Context.Item.ID.ToString())&@Html.Raw(SettingsHelper.ContextDeviceIdQueryStringKey)=@Html.Raw(Sitecore.Context.Device.ID.ToString())&@Html.Raw(SettingsHelper.CurrentWebsiteStringKey)=@Html.Raw(Sitecore.Context.Site.Name)&sc_preventProfilesScoring=1&sc_lang=@Html.Raw(Sitecore.ExperienceExplorer.Web.Controls.ExpExplorerExtender.LanguageName)" id="IframeExperienceExplorerViewer" class="ee-iframe"></iframe>
        </div>
    </div>

    <script src="/sitecore modules/Web/ExperienceExplorer/Assets/experience-explorer.min.js"></script>
    }
}

Sitecore81Sample/Views/Shared/MainLayout.cshtml
@{
    Layout = "~/Views/Shared/_BaseLayout.cshtml";
}

@Html.Sitecore().Placeholder("content")

Sitecore81Sample/Views/Shared/MainLayoutEmpty.cshtml
@{
    Layout = "~/Views/Shared/_BaseLayoutEmpty.cshtml";
}

@Html.Sitecore().Placeholder("content")

Sitecore81Sample/Views/Shared/_BaseLayout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Sitecore.Context.Item["Title"]</title>
    <meta name="description" content="@Sitecore.Context.Item["Meta Description"]" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
        integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link href="/Content/Site.min.css" rel="stylesheet" />
    @Html.Sitecore().VisitorIdentification()
</head>
<body id="body">
    <header id="header">@Html.Action("MainNavigation", "Navigation")</header>
    <div class="body-content">@RenderBody()</div>
    <footer id="footer">@Html.Action("FooterNavigation", "Navigation")</footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="/Scripts/media.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</body>
</html>

Sitecore81Sample/Views/Shared/_BaseLayoutEmpty.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@Sitecore.Context.Item["Title"]</title>
    <meta name="description" content="@Sitecore.Context.Item["Meta Description"]" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
        integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link href="/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/generics.css" rel="stylesheet" />
    <link href="~/Content/landingpage.css" rel="stylesheet" />
    @Html.Sitecore().VisitorIdentification()
</head>
<body id="body">
    <div class="body-content">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="/Scripts/media.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</body>
</html>